remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Kingtog Technology Co., Ltd 
description:  Welcome to our App studio.
show_downloads: false


